services:
  - type: web
    name: cerebroguard
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GRAPH_PATH
        value: data/enron_graph.graphml